### ISSUE TITLE
🐛 Bug Report: Reddit error 500 "null": "Internal Server Error"

### ISSUE THREAD

**Issue by APT37** [redlib-org/redlib#251]
happy times.

happens on all routes I tried so far.

not fixed by restarts. tested with multiple IPs. likely not an IP ban.

`Reddit error 500 "null": "Internal Server Error" | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL`

`Reddit error 500 "null": "Internal Server Error" | /r/all/hot.json?&raw_json=1`

<details>

<summary>cargo test</summary>

```
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.17s
Running unittests src/main.rs (target/debug/deps/redlib-c8a1401a107c7dfd)

running 42 tests
test config::test_deserialize ... ok
test config::test_alt_env_config_precedence ... ok
test config::test_alt_env_config_precedence ... ok
test config::test_config ... ok
test config::test_config ... ok
test config::test_default_filters ... ok
test config::test_config_legacy ... ok
test config::test_default_subscriptions ... ok
test config::test_default_filters ... ok
test config::test_config_legacy ... ok
test config::test_default_subscriptions ... ok
test config::test_env_config_precedence ... ok
test oauth::test_creating_device ... ok
test server::tests::test_determine_compressor ... ok
test config::test_env_var ... ok
test config::test_env_config_precedence ... ok
test config::test_env_var ... ok
test config::test_pushshift ... ok
test config::test_env_var_legacy ... ok
test config::test_env_var_legacy ... ok
test config::test_pushshift ... ok
test utils::test_rewriting_emoji ... ok
test utils::test_url_path_basename ... ok
test utils::tests::format_num_works ... ok
test utils::tests::rewrite_urls_keeps_intentional_backslashes ... ok
test utils::tests::rewrite_urls_removes_backslashes_and_rewrites_url ... ok
test utils::test_rewriting_image_links ... ok
test utils::tests::test_format_url ... ok
test oauth::test_oauth_token_exists ... ok
test oauth::test_oauth_client ... ok
test oauth::test_oauth_headers_len ... ok
test oauth::test_oauth_client_refresh ... ok
test utils::test_fetching_nsfw_subreddit ... FAILED
test client::test_share_link_strip_json ... FAILED
test user::test_fetching_user ... ok
test utils::test_fetching_subreddit_quarantined ... FAILED
test client::test_localization_popular ... FAILED
test subreddit::test_fetching_subreddit ... ok
test utils::test_fetching_ws ... FAILED
test server::tests::test_compress_response ... ok
test subreddit::test_gated_and_quarantined ... ok
test client::test_obfuscated_share_link ... ok

failures:

---- utils::test_fetching_nsfw_subreddit stdout ----
src/client.rs:315: GET https://oauth.reddit.com/r/softies/.json?utm_campaign=redirect&utm_medium=desktop&utm_source=reddit&utm_name=random_nsfw_subreddit&raw_json=1: dispatch task is gone: runtime dropped the dispatch task
thread 'utils::test_fetching_nsfw_subreddit' panicked at src/utils.rs:1268:5:
assertion failed: subreddit.is_ok()

---- client::test_share_link_strip_json stdout ----
thread 'client::test_share_link_strip_json' panicked at src/client.rs:443:5:
assertion `left == right` failed
  left: Ok(None)
 right: Ok(Some("/r/nfl/comments/17krzvz/rapoport_sources_former_no_2_overall_pick/"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- utils::test_fetching_subreddit_quarantined stdout ----
thread 'utils::test_fetching_subreddit_quarantined' panicked at src/utils.rs:1261:5:
assertion failed: subreddit.is_ok()

---- client::test_localization_popular stdout ----
thread 'client::test_localization_popular' panicked at src/client.rs:427:58:
called `Result::unwrap()` on an `Err` value: "Reddit error 500 \"null\": \"Internal Server Error\" | /r/popular/hot.json?&raw_json=1&geo_filter=GLOBAL"

---- utils::test_fetching_ws stdout ----
thread 'utils::test_fetching_ws' panicked at src/utils.rs:1275:5:
assertion failed: subreddit.is_ok()


failures:
    client::test_localization_popular
    client::test_share_link_strip_json
    utils::test_fetching_nsfw_subreddit
    utils::test_fetching_subreddit_quarantined
    utils::test_fetching_ws

test result: FAILED. 37 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.21s

error: test failed, to rerun pass `--bin redlib`
```

</details>

**Comment by LucifersCircle** [comment]
I’m having this error too. A few minutes before this error I was getting an expired token error, restarted the container and now this is the only error that shows. 
![IMG_3459](https://github.com/user-attachments/assets/9fc63d24-151b-47cb-ab21-9962fb8c7caa)

**Comment by Victor239** [comment]
Is it just me or does https://old.reddit.com/ not even load at the moment?

**Comment by Shagon94** [comment]
https://old.reddit.com/r/all/ doesn't seem to load, or rather it loads when force clearing the cookies; perhaps they broke it?

**Comment by sigaloid** [comment]
Closing this (though feel free to discuss) since this is definitely a server issue.

**Comment by Handrail9** [comment]
I'm having this issue on my private instance. I run my instance behind a VPN, is this part of the issue for other people?

**Comment by LucifersCircle** [comment]
> I'm having this issue on my private instance. I run my instance behind a VPN, is this part of the issue for other people?

It’ll be happening for everyone since it’s an issue with reddit and not redlib.
